name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t myapp:latest .

    - name: Save Docker image as tar file
      run: |
        docker save myapp:latest -o myapp.tar

    - name: Create env.ini file
      run: |
        echo "[Telegram]" > env.ini
        echo "api_id=${{ secrets.prod_env.TELEGRAM_API_ID }}" >> env.ini
        echo "api_hash=${{ secrets.prod_env.TELEGRAM_API_HASH }}" >> env.ini
        echo "bot_token=${{ secrets.prod_env.TELEGRAM_BOT_TOKEN }}" >> env.ini
        echo "[Database]" >> env.ini
        echo "host=${{ secrets.prod_env.DATABASE_HOST }}" >> env.ini
        echo "database=${{ secrets.prod_env.DATABASE_NAME }}" >> env.ini
        echo "port=${{ secrets.prod_env.DATABASE_PORT }}" >> env.ini
        echo "username=${{ secrets.prod_env.DATABASE_USERNAME }}" >> env.ini
        echo "password=${{ secrets.prod_env.DATABASE_PASSWORD }}" >> env.ini
        echo "[OpenAI]" >> env.ini
        echo "api_key=${{ secrets.prod_env.OPENAI_API_KEY }}" >> env.ini
        echo "[DeepL]" >> env.ini
        echo "api_key=${{ secrets.prod_env.DEEPL_API_KEY }}" >> env.ini
        echo "[RunPod]" >> env.ini
        echo "api_key=${{ secrets.prod_env.RUNPOD_API_KEY }}" >> env.ini
        echo "url=${{ secrets.prod_env.RUNPOD_URL }}" >> env.ini
        echo "[Downloads]" >> env.ini
        echo "host=${{ secrets.prod_env.DOWNLOADS_HOST }}" >> env.ini
        echo "port=${{ secrets.prod_env.DOWNLOADS_PORT }}" >> env.ini

    - name: Transfer tar file and env.ini to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        source: "myapp.tar,env.ini"
        target: /home/${{ secrets.prod_env.VPS_USER }}/
        host: ${{ secrets.prod_env.VPS_HOST }}
        username: ${{ secrets.prod_env.VPS_USER }}
        key: ${{ secrets.prod_env.VPS_SSH_KEY }}
        overwrite: true

    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.prod_env.VPS_HOST }}
        username: ${{ secrets.prod_env.VPS_USER }}
        key: ${{ secrets.prod_env.VPS_SSH_KEY }}
        script: |
          docker load -i /home/${{ secrets.prod_env.VPS_USER }}/myapp.tar
          docker run -d -p 80:9091 --env-file /home/${{ secrets.prod_env.VPS_USER }}/env.ini --name telewhisper_evo myapp:latest