name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create env.ini file
      run: |
        cat <<EOL > env.ini
        [Telegram]
        api_id=${{ secrets.TELEGRAM_API_ID }}
        api_hash=${{ secrets.TELEGRAM_API_HASH }}
        bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }}
        
        [Database]
        host=${{ secrets.DATABASE_HOST }}
        database=${{ secrets.DATABASE_NAME }}
        port=${{ secrets.DATABASE_PORT }}
        username=${{ secrets.DATABASE_USERNAME }}
        password=${{ secrets.DATABASE_PASSWORD }}
        
        [OpenAI]
        api_key=${{ secrets.OPENAI_API_KEY }}
        
        [Local]
        use_local_whisper=True
        model_size=small
        
        [DeepL]
        api_key=${{ secrets.DEEPL_API_KEY }}
        
        [FireworksAI]
        api_key=${{ secrets.FIREWORKSAI_API_KEY }}
        url=${{ secrets.FIREWORKSAI_URL }}
        
        [RunPod]
        api_key=${{ secrets.RUNPOD_API_KEY }}
        url=${{ secrets.RUNPOD_URL }}
        
        [Payments]
        default_token=${{ secrets.PAYMENTS_DEFAULT_TOKEN }}
        
        [Downloads]
        host=${{ secrets.VPS_HOST }}
        port=${{ secrets.DOWNLOADS_PORT }}
        EOL

    - name: Tar project
      run: |
        tar -cvf project.tar.gz . env.ini

    - name: Transfer TAR file to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        source: "project.tar.gz"
        target: /home/${{ secrets.VPS_USER }}/
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        overwrite: true

    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          bash start_deploy.sh