name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create env.ini file
      run: |
        echo "[Telegram]" > env.ini
        echo "api_id=${{ secrets.TELEGRAM_API_ID }}" >> env.ini
        echo "api_hash=${{ secrets.TELEGRAM_API_HASH }}" >> env.ini
        echo "bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> env.ini
        echo "[Database]" >> env.ini
        echo "host=${{ secrets.DATABASE_HOST }}" >> env.ini
        echo "database=${{ secrets.DATABASE_NAME }}" >> env.ini
        echo "port=${{ secrets.DATABASE_PORT }}" >> env.ini
        echo "username=${{ secrets.DATABASE_USERNAME }}" >> env.ini
        echo "password=${{ secrets.DATABASE_PASSWORD }}" >> env.ini
        echo "[OpenAI]" >> env.ini
        echo "api_key=${{ secrets.OPENAI_API_KEY }}" >> env.ini
        echo "[DeepL]" >> env.ini
        echo "api_key=${{ secrets.DEEPL_API_KEY }}" >> env.ini
        echo "[RunPod]" >> env.ini
        echo "api_key=${{ secrets.RUNPOD_API_KEY }}" >> env.ini
        echo "url=${{ secrets.RUNPOD_URL }}" >> env.ini
        echo "[Downloads]" >> env.ini
        echo "host=${{ secrets.VPS_HOST }}" >> env.ini
        echo "port=${{ secrets.DOWNLOADS_PORT }}" >> env.ini

    - name: Build Docker image
      run: |
        docker build -t myapp:latest .

    - name: Save Docker image as tar file
      run: |
        sudo docker save myapp:latest -o myapp.tar
        sudo chmod 777 myapp.tar

    - name: Transfer TAR file to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        source: "myapp.tar"
        target: /home/${{ secrets.VPS_USER }}/
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        overwrite: true

    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          bash start_deploy.sh